Settings-Version: 0.4
ServerSettings:
  enable: true
  enableAutoUpdate: true
  enablePlayerSettings: true
  enableAutomaticChestProtection: true
  adminsIgnoreProtection: false
  MySQL:
    enable: false
    type: local
    host: localhost
    port: 3306
    database: blockown
    user: foo
    password: bar
PlayerSettings:
Update-Pending: false
