Settings-Version: 0
ServerSettings:
  enable: true
  disableInWorlds: []
  serverName:
  enableOwning: true
  disableOwningInWorlds: []
  autoSaveInterval: 1200
  enableOwnedBlockDrops: true
  PermissionNeeded:
    OwnThroughBlockPlace: false
    OwnThroughCommand: false
    UnownThroughCommand: false
    ProtectAndPrivatizeCommand: false
    FriendCommand: false
  Protection:
    enable: true
    cascadeCommands: false
    enableMessages: true
    onlyLeftClicks: false
    autoProtectChests: true
    autoProtectEverything: false
    Radius:
      radius: 3
      preventPlace: false
      preventBreak: false
  AutoUpdater:
    releaseType: release
    apiKey:
    interval: 1800
    broadcastToOperators: true
  MySQL:
    enable: false
    type: local
    host: localhost
    port: 3306
    database: blockown
    user: foo
    password: bar
  Economy:
    enable: false
    protectPrice: 2.0
    privatizePrice: 3.0
    ownSelectionPricePerBlock: 1.0
