Settings-Version: 0.3.9
ServerSettings:
  enable: true
  enablePlayerSettings: true
  enableAutomaticChestProtection: true
  adminsIgnoreProtection: false
  cascadeProtectionCommands: false
PlayerSettings:
