Settings-Version: 0.5.1
ServerSettings:
  enable: true
  autoSaveInterval: 1200
  enablePlayerSettings: true
  enableAutomaticChestProtection: true
  enableAutomaticUniversalProtection: false
  adminsIgnoreProtection: false
  cascadeProtectionCommands: false
  AutoUpdater:
    enableAutoUpdate: true
    apiKey:
    autoUpdateInterval: 1800
  MySQL:
    enable: false
    type: local
    host: localhost
    port: 3306
    database: blockown
    user: foo
    password: bar
PlayerSettings:
