Settings-Version: 0.6.0
ServerSettings:
  enable: true
  autoSaveInterval: 1200
  enablePlayerSettings: true
  enableAutomaticChestProtection: true
  enableAutomaticUniversalProtection: false
  adminsIgnoreProtection: false
  cascadeProtectionCommands: false
  disableInWorlds: []
  permissionNeededForProtectCommand: false
  permissionNeededForOwnCommand: false
  AutoUpdater:
    enableAutoUpdate: true
    apiKey:
    autoUpdateInterval: 1800
    broadcastToOperators: true
  MySQL:
    enable: false
    type: local
    host: localhost
    port: 3306
    database: blockown
    user: foo
    password: bar
Protection:
FriendLists:
PrivateBlocks:
