Settings-Version: 0.4.1
ServerSettings:
  enable: true
  enablePlayerSettings: true
  enableAutomaticChestProtection: true
  adminsIgnoreProtection: false
  cascadeProtectionCommands: false
  MySQL:
    enable: false
    type: local
    host: localhost
    port: 3306
    database: blockown
    user: foo
    password: bar
PlayerSettings:
