name: BlockOwn
version: 0.8b

author: Pheasn

main: com.github.pheasn.blockown.BlockOwn

softdepend: [ServerBase, WorldEdit, Vault]

commands:
    
  owner:
    
  own:
    
  unown:
   
  blockown:
    aliases: bo
  
  protect:
  
  unprotect:
  
  friend:
  
  unfriend:
  
  privatize:
    aliases: privatise
    
  unprivatize:
    aliases: unprivatise
    
  protection:
  
  makepoor: