name: BlockOwn
version: 0.3.8

author: Pheasn

main: me.pheasn.blockown.BlockOwn

commands:
    
  owner:
    
  own:
    
  unown:
   
  blockown:
  
  protect:
  
  unprotect:
  
  whitelist:

  unwhitelist:
  
  protection:
  
  makepoor: