name: BlockOwn
version: 0.5.3

author: Pheasn

softdepend: [WorldEdit]

main: me.pheasn.blockown.BlockOwn

commands:
    
  owner:
    
  own:
    
  unown:
   
  blockown:
    aliases: bo
  
  protect:
  
  unprotect:
  
  whitelist:

  unwhitelist:
  
  protection:
  
  makepoor: