Settings-Version: 0.7.2
ServerSettings:
  enable: true
  serverName:
  autoSaveInterval: 1200
  enablePlayerSettings: true
  enableProtectedMessages: true
  protectOnlyLeftClicks: false
  enableAutomaticChestProtection: true
  enableAutomaticUniversalProtection: false
  adminsIgnoreProtection: false
  cascadeProtectionCommands: false
  disableInWorlds: []
  permissionNeededForProtectCommand: false
  permissionNeededForOwnCommand: false
  permissionNeededForOwning: false
  radiusBlockPlaceDenied: 0
  enableOwnedBlockDrops: true
  AutoUpdater:
    enable: true
    releaseType: release
    apiKey:
    autoUpdateInterval: 1800
    broadcastToOperators: true
  MySQL:
    enable: false
    type: local
    host: localhost
    port: 3306
    database: blockown
    user: foo
    password: bar
  Economy:
    enable: false
    protectPrice: 2.0
    privatizePrice: 3.0
    ownSelectionPricePerBlock: 1.0
